# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351b34c09fa753b43d7e3dd378f13bfb66a4632dd3dd607a267a6c9372a3202d0bb573c81ffd84c01b245b0603d5169fd92bb7918212eebdec73502e79d5bd57

test:
  secret_key_base: 4b87b3ee0604d50324ae072434af8f9be7b4be7b1a48966b923a85caaced41abbf3331c0ba7bfcfe6bac75dd79147e9bc7a2fca9d2cec79dab17a14ca9b28b32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
